name = "registry4vela"
uuid = "f753f6c8-35cd-4917-b353-244f33990c55"
repo = "https://github.com/abhisrkckl/julia_registry.git"
description = "Private registry for vela"

[packages]
43c95830-f66f-43f3-8298-be5f3865d5b9 = { name = "GeometricUnits", path = "G/GeometricUnits" }
